services:
  server:
    image: "rancher/k3s:${K3S_VERSION:-latest}"
    stop_signal: SIGKILL
    command:
      - server
      - --disable=traefik
      - --disable=metrics-server
    tmpfs:
    - /run
    - /var/run
    ulimits:
      nproc: 65535
      nofile:
        soft: 65535
        hard: 65535
    privileged: true
    restart: always
    environment:
    - K3S_TOKEN=${K3S_TOKEN:?err}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    # used to write kubeconfig.yaml after cluster finishes starting
    - ./config:/output

    # used to configure k3s to read from the registry container
    - ./config/k3s-registries.yaml:/etc/rancher/k3s/registries.yaml
    ports:
    - 6443:6443   # Kubernetes API Server
    - 30000:30000 # Nginx Ingress

  registry-docker-io:
    image: registry:2
    restart: unless-stopped
    volumes:
    - ./data/registry-docker-io:/var/lib/registry
    - ./config/registry-docker-io.yaml:/etc/docker/registry/config.yml

  registry-k8s-io:
    image: registry:2
    restart: unless-stopped
    volumes:
    - ./data/registry-k8s-io:/var/lib/registry
    - ./config/registry-k8s-io.yaml:/etc/docker/registry/config.yml